spring:
  application:
    name: stockprice
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456

logging:
  level:
    root: info
    org.springframework.amqp.rabbit.core.RabbitAdmin: DEBUG